### ISSUE TITLE
numbers set to 0 fail required validation

### ISSUE THREAD

**Issue by lowe0292** [castle-dev/le-data#70]
```
Job Data: {"applicantData":{"_type":"Applicant","breakingLease":false,"desiredMoveInAtTimestamp":1489046400000,"email":"applicant11@en$
ercastle.com","evictions":0,"firstName":"Scott","foundCastleDescription":"facebook","hasBankAccount":true,"hasPets":false,"isFirstRent$
l":false,"lastName":"Lowe","monthlyIncome":3800,"phoneNumber":"9186850032","primaryApplicantEmployer":"castle","smoker":true},"session$
id":"-KdxotVlf_xzBFTQhbLU","user_id":"ce582fd2-c272-41c5-aa63-eb1176c13c2e"}
creating applicant...
Error: evictions is required but was set to undefined on the LeData object, data: {"_type":"Applicant","breakingLease":false,"email":"$
pplicant11@entercastle.com","evictions":0,"firstName":"Scott","foundCastleDescription":"facebook","hasBankAccount":true,"hasPets":fals$
,"isFirstRental":false,"lastName":"Lowe","monthlyIncome":3800,"phoneNumber":"9186850032","primaryApplicantEmployer":"castle","smoker":$
rue,"desiredMoveInAt":"2017-03-09T08:00:00.000Z"}
    at LeDataService.validateRequiredPropertyOnField (/Users/scott/workspace/robot/node_modules/le-data/src/le-data-service.js:1208:25$
    at LeDataService.validateField (/Users/scott/workspace/robot/node_modules/le-data/src/le-data-service.js:1117:36)
    at /Users/scott/workspace/robot/node_modules/le-data/src/le-data-service.js:1077:58
    at Promise._unwrap (/Users/scott/workspace/robot/node_modules/ts-promise/dist/lib/Promise.js:871:32)
    at Promise._unwrapper (/Users/scott/workspace/robot/node_modules/ts-promise/dist/lib/Promise.js:896:25)
    at CallQueue.flush (/Users/scott/workspace/robot/node_modules/ts-promise/dist/lib/async.js:41:13)
    at Async.flush (/Users/scott/workspace/robot/node_modules/ts-promise/dist/lib/async.js:101:31)
    at Async._scheduledFlush (/Users/scott/workspace/robot/node_modules/ts-promise/dist/lib/async.js:146:14)
    at Immediate.Async._flusher [as _onImmediate] (/Users/scott/workspace/robot/node_modules/ts-promise/dist/lib/async.js:55:52)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by lowe0292** [comment]
Same with required booleans set to false:

```
Sun Feb 26 2017 20:37:57 GMT-0800 (PST) Processing create-applicant job:
Job Data: {"applicantData":{"_type":"Applicant","breakingLease":false,"desiredMoveInAtTimestamp":1489046400000,"email":"applicant11@entercastle.com","evictions":0,"firstName":"Scott","foundCastleDescription":"facebook","hasBankAccount":true,"hasPets":false,"isFirstRental":false,"lastName":"Lowe","monthlyIncome":3800,"phoneNumber":"9186850032","primaryApplicantEmployer":"castle","smoker":true},"session_id":"-KdxotVlf_xzBFTQhbLU","user_id":"ce582fd2-c272-41c5-aa63-eb1176c13c2e"}
creating applicant...
Error: hasPets is required but was set to undefined on the LeData object, data: {"_type":"Applicant","breakingLease":false,"email":"applicant11@entercastle.com","evictions":0,"firstName":"Scott","foundCastleDescription":"facebook","hasBankAccount":true,"hasPets":false,"isFirstRental":false,"lastName":"Lowe","monthlyIncome":3800,"phoneNumber":"9186850032","primaryApplicantEmployer":"castle","smoker":true,"desiredMoveInAt":"2017-03-09T08:00:00.000Z"}
    at LeDataService.validateRequiredPropertyOnField (/Users/scott/workspace/robot/node_modules/le-data/src/le-data-service.js:1208:25)
    at LeDataService.validateField (/Users/scott/workspace/robot/node_modules/le-data/src/le-data-service.js:1117:36)
    at /Users/scott/workspace/robot/node_modules/le-data/src/le-data-service.js:1077:58
    at Promise._unwrap (/Users/scott/workspace/robot/node_modules/ts-promise/dist/lib/Promise.js:871:32)
    at Promise._unwrapper (/Users/scott/workspace/robot/node_modules/ts-promise/dist/lib/Promise.js:896:25)
    at CallQueue.flush (/Users/scott/workspace/robot/node_modules/ts-promise/dist/lib/async.js:41:13)
    at Async.flush (/Users/scott/workspace/robot/node_modules/ts-promise/dist/lib/async.js:101:31)
    at Async._scheduledFlush (/Users/scott/workspace/robot/node_modules/ts-promise/dist/lib/async.js:146:14)
    at Immediate.Async._flusher [as _onImmediate] (/Users/scott/workspace/robot/node_modules/ts-promise/dist/lib/async.js:55:52)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```
